import requests
import json
import smtplib
import os
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# --- KONFIGURASI ---
IDX_API_URL = "https://www.idx.co.id/primary/NewsAnnouncement/GetNewsAnnouncement"

# Kata kunci filter (Multibagger Potential)
KEYWORDS = [
    "pengambilalihan", "akuisisi", "tender offer", 
    "pembelian saham", "investor strategis", "negosiasi",
    "divestasi", "pemenang tender", "kontrak baru", 
    "pelunasan utang", "menambah kepemilikan"
]

# Konfigurasi Email (Dari Environment Variable)
EMAIL_SENDER = os.environ.get("EMAIL_SENDER")     # Email pengirim (Gmail Anda)
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD") # App Password 16 digit
EMAIL_RECIPIENT = os.environ.get("EMAIL_RECIPIENT") # Email tujuan (Bisa sama dengan pengirim)

def send_email_alert(matches):
    if not EMAIL_SENDER or not EMAIL_PASSWORD:
        print("Email credentials not set. Skipping.")
        return

    # Buat Subjek Email
    subject = f"🚨 IDX Alert: {len(matches)} Potensi Multibagger Terdeteksi"
    
    # Buat Isi Email (Format HTML agar rapi)
    html_content = """
    <html>
    <body>
        <h2>Laporan Pantauan Saham Potensial</h2>
        <p>Berikut adalah keterbukaan informasi yang mengandung kata kunci strategis hari ini:</p>
        <table border="1" cellpadding="5" style="border-collapse: collapse; width: 100%;">
            <tr style="background-color: #f2f2f2;">
                <th>Kode</th>
                <th>Emiten</th>
                <th>Judul Pengumuman</th>
                <th>Link</th>
            </tr>
    """
    
    for item in matches:
        link = f"https://www.idx.co.id/id/berita/keterbukaan-informasi/" # Link detail spesifik butuh ID, ini link umum
        html_content += f"""
            <tr>
                <td><b>{item['code']}</b></td>
                <td>{item['name']}</td>
                <td>{item['title']}</td>
                <td><a href="{link}">Buka</a></td>
            </tr>
        """
    
    html_content += """
        </table>
        <p><i>Generated by Github Actions Bot</i></p>
    </body>
    </html>
    """

    # Setup MIME
    msg = MIMEMultipart()
    msg['From'] = "IDX Bot <" + EMAIL_SENDER + ">"
    msg['To'] = EMAIL_RECIPIENT
    msg['Subject'] = subject
    msg.attach(MIMEText(html_content, 'html'))

    # Proses Kirim via SMTP Gmail
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls() # Enkripsi
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        text = msg.as_string()
        server.sendmail(EMAIL_SENDER, EMAIL_RECIPIENT, text)
        server.quit()
        print("✅ Email sent successfully!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

def check_idx_news():
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "Referer": "https://www.idx.co.id/"
    }

    params = {
        "indexFrom": 0,
        "pageSize": 50,
        "year": datetime.now().year,
        "lang": "id"
    }

    print("Fetching data from IDX...")
    response = requests.get(IDX_API_URL, headers=headers, params=params)
    
    if response.status_code != 200:
        print(f"Error fetching: {response.status_code}")
        return

    data = response.json()
    results = data.get('Results', [])
    
    # List untuk menampung temuan
    found_matches = []

    # Filter Berita Hari Ini Saja
    today_str = datetime.now().strftime("%Y-%m-%d")

    for item in results:
        title = item.get('Title', '').lower()
        published_date = item.get('PublishedDate', '')[:10] # YYYY-MM-DD

        # Logika: Harus hari ini DAN mengandung keyword
        # Note: Github server pakai UTC. Jika ingin pas WIB, perlu penyesuaian jam.
        # Untuk simpelnya, kita ambil semua yang tanggalnya 'hari ini' di server.
        
        if published_date == today_str: 
            if any(keyword in title for keyword in KEYWORDS):
                print(f"MATCH: {item.get('EmitenCode')} - {item.get('Title')}")
                found_matches.append({
                    'code': item.get('EmitenCode'),
                    'name': item.get('EmitenName'),
                    'title': item.get('Title'),
                    'date': published_date
                })

    # Jika ada temuan, kirim email
    if found_matches:
        send_email_alert(found_matches)
    else:
        print("No matches found today.")

if __name__ == "__main__":
    check_idx_news()